apiVersion: apps/v1
kind: Deployment
metadata:
  name: santos-denisags
spec:
  replicas: 1
  selector:
    matchLabels:
      app: santos-denisags
  template:
    metadata:
      labels:
        app: santos-denisags
    spec:
      containers:
      - image: okteto.dev/santos-denisags:latest
        name: santos-denisags
        envFrom:
        - configMapRef:
            name: santos-denisags-config
        livenessProbe:
          httpGet:
            path: /ht/
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5
---

apiVersion: v1
kind: Service
metadata:
  name: denisags
  annotations:
    dev.okteto.com/auto-ingress: "true"
spec:
  type: ClusterIP  
  ports:
  - name: "santos-denisags"
    port: 8080
  selector:
    app: santos-denisags
